name: Docker-Release-Downloader
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 必须开启写入权限以创建 Release
    steps:
      - name: Pull and Save
        run: |
          docker pull smanx/openclaw:latest
          docker pull redis:alpine
          docker tag smanx/openclaw:latest openclaw:local
          docker save openclaw:local redis:alpine -o openclaw_images.tar
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: OpenClaw Offline Package ${{ github.run_number }}
          files: openclaw_images.tar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
